# SOCIAL_AUTH_TWITTER_KEY = 'XXXXXXXXXXXXXXX'
# SOCIAL_AUTH_TWITTER_SECRET = 'YYYYYYYYYYYYYY'

# CONSUMER_KEY = "mXAtQH6u0iQgEvaJC6ilxLqP0"
# CONSUMER_SECRET = "ngANEzIGDX07GBg6qmx0eCRED3bc7JyjczHkGNNrHBCvQDXyPL"

# SOCIAL_AUTH_TWITTER_KEY = 'cAXVHPD1cHPfXH2q9S83spYHH'
# SOCIAL_AUTH_TWITTER_SECRET = 'gKBD3vf0NB4KeHZCP2ryTFchB7OrpIjF20DPU7sazh9ckI2HHS'
SOCIAL_AUTH_TWITTER_KEY = 'mXAtQH6u0iQgEvaJC6ilxLqP0'
SOCIAL_AUTH_TWITTER_SECRET = 'ngANEzIGDX07GBg6qmx0eCRED3bc7JyjczHkGNNrHBCvQDXyPL'
